export type ArcanaType = 'major' | 'minor'
export type TarotSuit = 'cups' | 'wands' | 'swords' | 'pentacles'
export type CardPosition = 'past' | 'present' | 'future'

export interface TarotCardData {
  id: string
  name: string
  englishName: string
  arcana: ArcanaType
  suit?: TarotSuit
  number: number
  numeral: string
  symbol: string
  keywords: string[]
  meaning: string
  pastMeaning: string
  presentMeaning: string
  futureMeaning: string
}

export interface DrawnTarotCard extends TarotCardData {
  position: CardPosition
  positionTitle: string
}

export const TAROT_DECK: TarotCardData[] = [
  // ────────────────────────────────────────────────────────────
  // 22 BÜYÜK ARKANA (MAJOR ARCANA)
  // ────────────────────────────────────────────────────────────
  {
    id: 'major-0',
    name: 'Deli',
    englishName: 'The Fool',
    arcana: 'major',
    number: 0,
    numeral: '0',
    symbol: '🎒',
    keywords: ['Yeni Başlangıçlar', 'Masumiyet', 'Cesaret', 'Özgür Ruh'],
    meaning: 'Hayatında yepyeni ve beklenmedik bir sayfa açılıyor. İçindeki sese güven ve tereddüt etmeden adım at.',
    pastMeaning: 'Geçmişte aldığın ani bir karar veya sıfırdan başlama cesareti seni bugünkü deneyimlerine taşıdı.',
    presentMeaning: 'Şu anda ön yargılardan arınarak yeni fırsatlara kalbini açma ve içgüdülerine güvenme vaktindesin.',
    futureMeaning: 'Gelecekte seni heyecan dolu, kuralları yeniden yazacağın özgür bir yolculuk ve yenilenme bekliyor.',
  },
  {
    id: 'major-1',
    name: 'Büyücü',
    englishName: 'The Magician',
    arcana: 'major',
    number: 1,
    numeral: 'I',
    symbol: '🪄',
    keywords: ['İrade', 'Yaratıcılık', 'Beceriklilik', 'Tezahür'],
    meaning: 'İstediğin gerçeği yaratmak için gereken tüm yetenek ve kaynaklara zaten sahipsin. Odaklan ve harekete geç.',
    pastMeaning: 'Geçmişte zekanı ve yaratıcı yeteneklerini kullanarak önemli bir engeli aşmayı başardın.',
    presentMeaning: 'Tüm niyetlerini gerçeğe dönüştürmek için güçlü bir enerji alanındasın; fikirlerini eyleme dök.',
    futureMeaning: 'Girişimlerin meyvesini verecek ve hayal ettiğin başarıyı kendi ellerinle inşa edeceksin.',
  },
  {
    id: 'major-2',
    name: 'Azize',
    englishName: 'The High Priestess',
    arcana: 'major',
    number: 2,
    numeral: 'II',
    symbol: '🌙',
    keywords: ['Sezgi', 'Gizem', 'Bilinçaltı', 'İçsel Bilgelik'],
    meaning: 'Cevaplar dışarıda değil, iç sesinin fısıltısında gizli. Mantığından önce kalbinin ve rüyalarının rehberliğine kulak ver.',
    pastMeaning: 'Geçmişte farkında olmadan hissettiğin sezgiler seni doğru yöne sevk etti.',
    presentMeaning: 'Şu an acele kararlar verme zamanı değil; sakin kalıp perde arkasındaki gerçekleri gözlemle.',
    futureMeaning: 'Zamanla gizli olan her şey aydınlanacak ve derin bir iç huzura ve farkındalığa kavuşacaksın.',
  },
  {
    id: 'major-3',
    name: 'İmparatoriçe',
    englishName: 'The Empress',
    arcana: 'major',
    number: 3,
    numeral: 'III',
    symbol: '🌸',
    keywords: ['Bereket', 'Şefkat', 'Güzellik', 'Doğurganlık'],
    meaning: 'Sevginin, şefkatin ve bolluğun zirve yaptığı bir evre. Hayatına giren güzellikleri kucakla ve kendini besle.',
    pastMeaning: 'Geçmişte ektiğin sevgi tohumları ve gösterdiğin sabır bugünün bereketini hazırladı.',
    presentMeaning: 'Aşk, ilişkiler ve yaratıcılık alanında derin bir uyum ve sıcaklık içindesin.',
    futureMeaning: 'Hayatında bolluk, neşe ve duygusal doyum dolu çok verimli bir dönem kapıda.',
  },
  {
    id: 'major-4',
    name: 'İmparator',
    englishName: 'The Emperor',
    arcana: 'major',
    number: 4,
    numeral: 'IV',
    symbol: '👑',
    keywords: ['Otorite', 'Düzen', 'Liderlik', 'İstikrar'],
    meaning: 'Kararlılık, sınırlar ve disiplin zamanı. Hayatının kontrolünü eline al ve sağlam temeller inşa et.',
    pastMeaning: 'Geçmişte kurduğun düzen ve gösterdiğin sağlam duruş sana bugünkü gücünü kazandırdı.',
    presentMeaning: 'Duyguların karmaşasını net bir plan ve kararlılıkla yönetmen gereken bir andasın.',
    futureMeaning: 'Uzun vadeli güven ve saygınlık kazanacak, arzuladığın istikrara kavuşacaksın.',
  },
  {
    id: 'major-5',
    name: 'Aziz',
    englishName: 'The Hierophant',
    arcana: 'major',
    number: 5,
    numeral: 'V',
    symbol: '📜',
    keywords: ['Gelenek', 'Öğreti', 'Maneviyat', 'Rehberlik'],
    meaning: 'Bilgelik arayışı ve değerlerine sadakat. Güvendiğin bir rehberin tecrübesi sana yol gösterecektir.',
    pastMeaning: 'Aileden veya güvendiğin bir mentorun öğütlerinden aldığın dersler bugünkü bakış açını şekillendirdi.',
    presentMeaning: 'Toplumsal bağlar, ortak değerler ve içsel inançlarınla uyum içinde hareket etmelisin.',
    futureMeaning: 'Derin bir ruhsal arınma yaşayacak ve başkalarına da ilham veren bir duruş kazanacaksın.',
  },
  {
    id: 'major-6',
    name: 'Aşıklar',
    englishName: 'The Lovers',
    arcana: 'major',
    number: 6,
    numeral: 'VI',
    symbol: '💖',
    keywords: ['Aşk', 'Uyum', 'Seçim', 'Ruh Eşi'],
    meaning: 'Kalpten gelen derin bir bağ ve hayatını değiştirecek önemli bir seçim. Aşk ve dürüstlük yol göstericin olsun.',
    pastMeaning: 'Geçmişte verdiğin bir sevgi kararı kalbinin rotasını kökten değiştirdi.',
    presentMeaning: 'İlişkilerinde samimiyet, tutku ve karşılıklı güvenin sınandığı veya pekiştiği bir eşiktesin.',
    futureMeaning: 'Ruhunu tamamlayan bir bağ kurulacak ve kalbinle mantığın kusursuz bir uyum yakalayacak.',
  },
  {
    id: 'major-7',
    name: 'Araba',
    englishName: 'The Chariot',
    arcana: 'major',
    number: 7,
    numeral: 'VII',
    symbol: '🐎',
    keywords: ['Zafer', 'İlerleme', 'Azim', 'Kontrol'],
    meaning: 'Çelişkili durumları dizginleyip hedefe doğru hızla ilerleme zamanı. Kararlılığın zafer getirecektir.',
    pastMeaning: 'Zorlu koşullara rağmen pes etmeyip direndiğin için bugünkü noktaya ulaştın.',
    presentMeaning: 'Odak noktanı kaybetmeden tam gaz ilerlemeli, tereddütleri bir kenara bırakmalısın.',
    futureMeaning: 'Karşına çıkan engeller birer birer aşılacak ve hak ettiğin başarıyı kutlayacaksın.',
  },
  {
    id: 'major-8',
    name: 'Güç',
    englishName: 'Strength',
    arcana: 'major',
    number: 8,
    numeral: 'VIII',
    symbol: '🦁',
    keywords: ['İçsel Güç', 'Cesaret', 'Şefkat', 'Sabır'],
    meaning: 'Gerçek güç kaba kuvvette değil, sevgiyle yönlendirilen sabır ve zarafette yatar.',
    pastMeaning: 'Zor bir dönemi öfkeyle değil, olgunluk ve şefkatle atlattın.',
    presentMeaning: 'Korkularının üzerine sevgiyle git; içindeki cesaret her türlü zorluğun üstesinden gelecek güçte.',
    futureMeaning: 'Fırtınalar dinecek ve sarsılmaz bir özgüvenle geleceğe güvenle bakacaksın.',
  },
  {
    id: 'major-9',
    name: 'Ermiş',
    englishName: 'The Hermit',
    arcana: 'major',
    number: 9,
    numeral: 'IX',
    symbol: '🏮',
    keywords: ['İçsel Arayış', 'Yalnızlık', 'Aydınlanma', 'Farkındalık'],
    meaning: 'Gürültüden uzaklaşıp kendi içine dönme vakti. Kendi fenerin yolunu aydınlatmaya yetecektir.',
    pastMeaning: 'Geçmişteki yalnızlık ve derin düşünce dönemleri ruhuna derin bir bilgelik kattı.',
    presentMeaning: 'Dış sesleri kapatıp ne istediğini gerçekten anlamak için kendine özel zaman ayırmalısın.',
    futureMeaning: 'Karanlıkta kalan sorular netleşecek ve hayatının gerçek amacını daha berrak göreceksin.',
  },
  {
    id: 'major-10',
    name: 'Kader Çarkı',
    englishName: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    numeral: 'X',
    symbol: '☸️',
    keywords: ['Kader', 'Döngüler', 'Şans', 'Değişim'],
    meaning: 'Hayatın çarkı senin lehindeki dönmeye başlıyor. Değişime direnme, evrenin akışına teslim ol.',
    pastMeaning: 'Kontrolün dışında gelişen bir dönüm noktası seni bu yeni başlangıca hazırladı.',
    presentMeaning: 'Beklenmedik bir fırsat veya tesadüf kapını çalabilir; şansını iyi değerlendir.',
    futureMeaning: 'Talih yüzüne gülecek ve karma senin için olumlu bir döngüyü başlatacak.',
  },
  {
    id: 'major-11',
    name: 'Adalet',
    englishName: 'Justice',
    arcana: 'major',
    number: 11,
    numeral: 'XI',
    symbol: '⚖️',
    keywords: ['Denge', 'Dürüstlük', 'Hak', 'Karma'],
    meaning: 'Hak yerini bulur. Dürüstlükle atılan her adım sana huzur ve adil bir sonuç getirecektir.',
    pastMeaning: 'Geçmişte yaptığın doğru ve dürüst seçimlerin ödülünü bugün topluyorsun.',
    presentMeaning: 'Taraf tutmadan, objektif ve net bir vicdanla karar vermen gereken kritik bir andasın.',
    futureMeaning: 'Haksızlıklar son bulacak, hak ettiğin değer ve adalet hayatında tecelli edecek.',
  },
  {
    id: 'major-12',
    name: 'Asılan Adam',
    englishName: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    numeral: 'XII',
    symbol: '⏳',
    keywords: ['Farklı Bakış', 'Teslimiyet', 'Bekleme', 'Fedakarlık'],
    meaning: 'Bazen ilerlemenin tek yolu durmaktır. Durumu farklı bir açıdan gör ve kontrolü biraz serbest bırak.',
    pastMeaning: 'Geçmişte askıya alınan veya bekletilen bir konu sana sabrı ve yeni bir bakış açısını öğretti.',
    presentMeaning: 'Şu an zorlamak yerine olayları akışına bırakmalı, olaylara tersten bakmayı denemelisin.',
    futureMeaning: 'Bekleyiş sona erecek ve kazandığın aydınlanmayla hızla ilerlemeye başlayacaksın.',
  },
  {
    id: 'major-13',
    name: 'Ölüm',
    englishName: 'Death',
    arcana: 'major',
    number: 13,
    numeral: 'XIII',
    symbol: '🦋',
    keywords: ['Dönüşüm', 'Bitiş', 'Yeniden Doğuş', 'Arınma'],
    meaning: 'Fiziksel ölüm değil, köklü bir yeniden doğuş. Artık sana hizmet etmeyen eskiyi bırak ki yeni gelebilsin.',
    pastMeaning: 'Geçmişte kapanan bir kapı acı vermiş olsa da sana bambaşka bir yaşam alanı açtı.',
    presentMeaning: 'Eski alışkanlıkları, korkuları veya bitmiş bağları geride bırakma cesareti göstermelisin.',
    futureMeaning: 'Tırtılın kelebeğe dönüşmesi gibi, hayatında pırıl pırıl ve taze bir dönem başlayacak.',
  },
  {
    id: 'major-14',
    name: 'Denge',
    englishName: 'Temperance',
    arcana: 'major',
    number: 14,
    numeral: 'XIV',
    symbol: '🕊️',
    keywords: ['Uyum', 'Ölçü', 'Şifa', 'Sakinlik'],
    meaning: 'Aşırılıklardan uzak durma ve iki zıt kutbu barış içinde harmanlama zamanı. İçsel şifa seninle.',
    pastMeaning: 'Geçmişte gösterdiğin sabır ve ılımlılık fırtınaları dindirdi.',
    presentMeaning: 'Duygularınla aklını dengelemeli, aceleci tepkiler yerine sakinliği seçmelisin.',
    futureMeaning: 'Ruhsal dinginlik, uyumlu ilişkiler ve uzun soluklu bir esenlik hayatına yerleşecek.',
  },
  {
    id: 'major-15',
    name: 'Şeytan',
    englishName: 'The Devil',
    arcana: 'major',
    number: 15,
    numeral: 'XV',
    symbol: '⛓️',
    keywords: ['Bağımlılık', 'Gölge Yanlar', 'Tutsaklık', 'Yanılsama'],
    meaning: 'Seni zincirleyen korkular ve takıntılar aslında birer yanılsama. Zincirlerini kırmak senin elinde.',
    pastMeaning: 'Geçmişte seni sınırlandıran sağlıksız bir bağ veya alışkanlık iz bıraktı.',
    presentMeaning: 'Kendi arzularını sorgula; tutku ile bağımlılık arasındaki ince çizgiyi fark et.',
    futureMeaning: 'Kendi gölgelerinle yüzleşip özgürleştiğinde inanılmaz bir güç ve hafiflik kazanacaksın.',
  },
  {
    id: 'major-16',
    name: 'Yıkılan Kule',
    englishName: 'The Tower',
    arcana: 'major',
    number: 16,
    numeral: 'XVI',
    symbol: '⚡',
    keywords: ['Ani Değişim', 'Uyanış', 'Yıkım', 'Özgürleşme'],
    meaning: 'Çürük temeller üzerine kurulu her şey bir şimşekle yıkılır. Bu yıkım seni sahteliklerden kurtaracak.',
    pastMeaning: 'Geçmişte yaşanan sarsıcı bir sürpriz seni gerçeklerle yüzleştirdi.',
    presentMeaning: 'Kontrol edemediğin ani değişimlere direnme; bırak eski yıkılsın, gerçeğin temeli kalsın.',
    futureMeaning: 'Küllerinden yeniden doğacak ve hayatını çok daha sağlam, dürüst bir zemin üzerine kuracaksın.',
  },
  {
    id: 'major-17',
    name: 'Yıldız',
    englishName: 'The Star',
    arcana: 'major',
    number: 17,
    numeral: 'XVII',
    symbol: '⭐',
    keywords: ['Umut', 'İlham', 'İyileşme', 'İnanç'],
    meaning: 'Karanlığın ardından parlayan umut ışığı. Evren sana rehberlik ediyor, hayallerine ve geleceğe güven.',
    pastMeaning: 'Zor bir dönemin ardından kalbinde filizlenen umut seni bugünlere taşıdı.',
    presentMeaning: 'Şu an kalbini şifalandırma, tazelenme ve saf niyetlerle dilek dileme zamanı.',
    futureMeaning: 'Dileklerin gerçeğe dönüşecek ve hayatın ilham ve huzurla parıldayacak.',
  },
  {
    id: 'major-18',
    name: 'Ay',
    englishName: 'The Moon',
    arcana: 'major',
    number: 18,
    numeral: 'XVIII',
    symbol: '🐺',
    keywords: ['İllüzyon', 'Bilinmeyen', 'Bilinçaltı', 'Korkular'],
    meaning: 'Sisli bir yoldasın; her şey göründüğü gibi olmayabilir. Korkularınla yüzleş ve içgüdülerine güven.',
    pastMeaning: 'Geçmişte yaşadığın belirsizlikler sende derin bir hassasiyet bıraktı.',
    presentMeaning: 'Görünürdeki aldatıcı görüntülere kanma; sezgilerini kullanarak gerçeği ara.',
    futureMeaning: 'Sis perdesi dağılacak, gizli kalan sırlar gün ışığına çıkacak ve aydınlanacaksın.',
  },
  {
    id: 'major-19',
    name: 'Güneş',
    englishName: 'The Sun',
    arcana: 'major',
    number: 19,
    numeral: 'XIX',
    symbol: '☀️',
    keywords: ['Neşe', 'Aydınlık', 'Başarı', 'Yaşam Enerjisi'],
    meaning: 'Tarotun en pozitif kartlarından biri! Karanlıklar bitti; mutluluk, başarı ve canlılık seni kucaklıyor.',
    pastMeaning: 'Geçmişteki samimi çabaların ve pozitif tutumun bugünkü mutluluğuna zemin hazırladı.',
    presentMeaning: 'Işıl ışıl parladığın, özgüven ve coşku dolu bir andasın; hayatın tadını çıkar.',
    futureMeaning: 'Kutlamalar, mutluluk ve her alanda tam bir zafer ve neşe seni bekliyor.',
  },
  {
    id: 'major-20',
    name: 'Mahkeme',
    englishName: 'Judgement',
    arcana: 'major',
    number: 20,
    numeral: 'XX',
    symbol: '🎺',
    keywords: ['Uyanış', 'Hesaplaşma', 'Yeniden Doğuş', 'Çağrı'],
    meaning: 'İçsel bir uyanış ve kader çağrısı. Geçmişin yüklerini affet ve yeni benliğini kucakla.',
    pastMeaning: 'Geçmişteki hatalarından büyük dersler çıkararak kendini yeniden tanımladın.',
    presentMeaning: 'Kendi gerçeğinle yüzleşme ve hayatının yeni dönemine uyanma anındasın.',
    futureMeaning: 'Vicdanın rahat, ruhun hafif bir şekilde hayatının en yüce versiyonuna adım atacaksın.',
  },
  {
    id: 'major-21',
    name: 'Dünya',
    englishName: 'The World',
    arcana: 'major',
    number: 21,
    numeral: 'XXI',
    symbol: '🌍',
    keywords: ['Tamamlanma', 'Bütünlük', 'Tatmin', 'Evrensel Uyum'],
    meaning: 'Büyük bir döngünün muhteşem tamamlanışı. Zafer, bütünlük ve dünyayla kusursuz bir ahenk.',
    pastMeaning: 'Büyük bir hedefi başarıyla tamamladın ve olgunlaştın.',
    presentMeaning: 'Emeğinin karşılığını aldığın, parçaların yerine oturduğu huzurlu bir tamamlanma anı.',
    futureMeaning: 'Hayatındaki tüm arayışlar mutlu bir sona ulaşacak ve yeni, daha yüksek bir seviyeye geçeceksin.',
  },

  // ────────────────────────────────────────────────────────────
  // KUPALAR SUİTİ (CUPS) — DUYGULAR, AŞK & İLİŞKİLER (14 KART)
  // ────────────────────────────────────────────────────────────
  {
    id: 'cups-1',
    name: 'Kupa Ası',
    englishName: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    numeral: 'I',
    symbol: '🏆',
    keywords: ['Yeni Aşk', 'Duygusal Taşma', 'Şefkat', 'Sezgi'],
    meaning: 'Kalbinde yepyeni bir sevgi kaynağı kaynıyor. Duygusal bir başlangıç ve saf aşk seni sarıyor.',
    pastMeaning: 'Geçmişte kalbini açtığın o an hayatına taze bir sevgi akışı başlattı.',
    presentMeaning: 'Duygularını cesurca ifade etme ve yeni bir aşka ya da dostluğa kucak açma zamanı.',
    futureMeaning: 'Ruhunu besleyen derin bir aşk bağı ve duygusal huzur seni bekliyor.',
  },
  {
    id: 'cups-2',
    name: 'Kupa İkilisi',
    englishName: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    numeral: 'II',
    symbol: '🥂',
    keywords: ['Ruh Bağı', 'Karşılıklı Sevgi', 'Ortaklık', 'Çekim'],
    meaning: 'İki kalbin birbiriyle uyum içinde atması. Karşılıklı sevgi, saygı ve güçlü bir ortaklık.',
    pastMeaning: 'Geçmişte biriyle kurduğun derin bağ bugün hala güven hissi veriyor.',
    presentMeaning: 'Partnerinle veya yakın bir dostunla mükemmel bir empati ve yakınlaşma içindesin.',
    futureMeaning: 'Karşılıklı aşkın ve bağın güçleneceği, resmiyete dökülebilecek bir uyum dönemi.',
  },
  {
    id: 'cups-3',
    name: 'Kupa Üçlüsü',
    englishName: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    numeral: 'III',
    symbol: '🎉',
    keywords: ['Kutlama', 'Dostluk', 'Birliktelik', 'Neşe'],
    meaning: 'Dostlarla bir araya gelip sevinci paylaşma vakti. Ortak mutluluklar ve kutlamalar seni bekliyor.',
    pastMeaning: 'Sana destek olan dostlarının sevgisiyle zor günleri geride bıraktın.',
    presentMeaning: 'Arkadaşlarınla vakit geçirmeli, neşeli haberleri birlikte kutlamalısın.',
    futureMeaning: 'Sosyal çevrende neşe dolu buluşmalar ve kutlanacak harika haberler var.',
  },
  {
    id: 'cups-4',
    name: 'Kupa Dörtlüsü',
    englishName: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    numeral: 'IV',
    symbol: '🪷',
    keywords: ['İçine Kapanma', 'Fırsatları Görememe', 'Tatsızlık', 'Durgunluk'],
    meaning: 'Önündeki nimetleri görmezden gelip içsel bir tatminsizliğe kapılmış olabilirsin. Başını kaldır ve etrafına bak.',
    pastMeaning: 'Geçmişteki bir kırgınlık yüzünden bir süre kendini insanlardan soyutladın.',
    presentMeaning: 'Sana sunulan yeni bir fırsatı fark etmelisin; ilgisizlik seni fırsatlardan mahrum bırakmasın.',
    futureMeaning: 'Mevcut sıkıntından uyanacak ve sana uzatılan sevgi dolu eli fark edeceksin.',
  },
  {
    id: 'cups-5',
    name: 'Kupa Beşlisi',
    englishName: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    numeral: 'V',
    symbol: '🥀',
    keywords: ['Kayıp', 'Pişmanlık', 'Keder', 'Kalan Umut'],
    meaning: 'Dökülen kupalara üzülürken arkanda dimdik duran iki kupayı unutma. Umut asla tükenmez.',
    pastMeaning: 'Geçmişteki bir hayal kırıklığının kederi uzun süre etkisinde bıraktı.',
    presentMeaning: 'Olmayana odaklanmayı bırakıp elinde kalan güzelliklere ve geleceğe sarılmalısın.',
    futureMeaning: 'Yaraların sarılacak ve kaybettiğinden çok daha değerlisini hayatına çekeceksin.',
  },
  {
    id: 'cups-6',
    name: 'Kupa Altılısı',
    englishName: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    numeral: 'VI',
    symbol: '🧸',
    keywords: ['Nostalji', 'Çocukluk', 'Masumiyet', 'Eski Anılar'],
    meaning: 'Geçmişten gelen tatlı bir esinti, eski bir dost ya da çocukluk masumiyetinin hatırlanması.',
    pastMeaning: 'Geçmişin güzel anıları ve köklerin sana her zaman güvenli bir liman oldu.',
    presentMeaning: 'Eski bir tanıdıktan haber alabilir veya geçmişin samimiyetini yeniden yaşayabilirsin.',
    futureMeaning: 'Saf ve hesapsız bir sevgi hayatına girecek, kalbini ısıtacak.',
  },
  {
    id: 'cups-7',
    name: 'Kupa Yedilisi',
    englishName: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    numeral: 'VII',
    symbol: '💭',
    keywords: ['Hayaller', 'Seçenekler', 'İllüzyon', 'Kararsızlık'],
    meaning: 'Önünde birçok cazip seçenek var ama hepsi gerçek değil. Hayallerle gerçeği ayırt etmelisin.',
    pastMeaning: 'Geçmişte çok fazla hayale kapılıp odaklanmakta zorlandığın anlar oldu.',
    presentMeaning: 'Ayaklarını yere basmalı ve en gerçekçi, kalbine en yakın seçeneği seçmelisin.',
    futureMeaning: 'Zihnindeki karmaşa dağılacak ve doğru hedefe kararlılıkla odaklanacaksın.',
  },
  {
    id: 'cups-8',
    name: 'Kupa Sekizlisi',
    englishName: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    numeral: 'VIII',
    symbol: '🚶‍♂️',
    keywords: ['Terk Etme', 'Arayış', 'Yola Çıkma', 'Daha İyisini Arama'],
    meaning: 'Artık seni tatmin etmeyen bir durumu arkanda bırakıp daha derin anlamlar aramak için yola çıkıyorsun.',
    pastMeaning: 'Sana yetmeyen bir ortamdan cesaretle ayrıldın.',
    presentMeaning: 'Seni tüketmiş bir durumdan zarifçe uzaklaşma ve kendi yoluna gitme zamanı.',
    futureMeaning: 'Yüksek bir ruhsal amaca doğru ilerleyecek ve iç huzurunu bulacaksın.',
  },
  {
    id: 'cups-9',
    name: 'Kupa Dokuzlusu',
    englishName: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    numeral: 'IX',
    symbol: '✨',
    keywords: ['Dilek Kartı', 'Tatmin', 'Mutluluk', 'Şükran'],
    meaning: 'Dileklerinin gerçekleştiği, hem ruhsal hem maddesel olarak tam bir doyum yaşadığın altın an.',
    pastMeaning: 'İçtenlikle dilediğin bir şeyin gerçekleşmesi sana evrene güvenmeyi öğretti.',
    presentMeaning: 'Kendinle barışık, mutlu ve hayattan keyif aldığın harika bir dönemdesin.',
    futureMeaning: 'En çok istediğin dileğin kabul olacak ve büyük bir şükran hissi duyacaksın.',
  },
  {
    id: 'cups-10',
    name: 'Kupa Onlusu',
    englishName: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    numeral: 'X',
    symbol: '🌈',
    keywords: ['Kusursuz Mutluluk', 'Aile', 'Huzur', 'Duygusal Zirve'],
    meaning: 'Gökkuşağının altındaki yuva. Ailede, ilişkilerde ve kalpte sonsuz bir huzur ve bütünlük.',
    pastMeaning: 'Seni sevenlerin desteğiyle güvenli ve sevgi dolu bir temel inşa ettin.',
    presentMeaning: 'Sevdiklerinle birlikte tam bir uyum ve huzurun tadını çıkarıyorsun.',
    futureMeaning: 'Uzun vadeli, kalıcı bir yuva sıcaklığı ve duygusal mutluluk seni bekliyor.',
  },
  {
    id: 'cups-page',
    name: 'Kupa Prensi',
    englishName: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    numeral: 'Prens',
    symbol: '💌',
    keywords: ['Tatlı Mesaj', 'Sezgisellik', 'Yeni Duygular', 'Romantizm'],
    meaning: 'Beklenmedik tatlı bir haber, romantik bir jest veya sezgisel bir ilham kapını çalıyor.',
    pastMeaning: 'Geçmişte gelen samimi bir mesaj kalbini yumuşattı.',
    presentMeaning: 'Duygusal bir teklife veya yaratıcı bir ilhama açık ol.',
    futureMeaning: 'Kalbinde kelebekler uçuşturacak romantik bir haber ya da başlangıç yolda.',
  },
  {
    id: 'cups-knight',
    name: 'Kupa Şövalyesi',
    englishName: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    numeral: 'Şövalye',
    symbol: '🦢',
    keywords: ['Romantik Teklif', 'Zarafet', 'Hayalperest', 'Sevgi Daveti'],
    meaning: 'Beyaz atlı prens enerjisi! Kalpten gelen samimi bir teklif veya duygusal bir davet sana doğru geliyor.',
    pastMeaning: 'Geçmişte duygularının peşinden tutkuyla koştun.',
    presentMeaning: 'Hayallerine romantizm ve zarafetle yaklaş; bir sevgi itirafı gerçekleşebilir.',
    futureMeaning: 'Seni büyüleyecek bir sevgi adımı veya derin bir duygusal teklif alacaksın.',
  },
  {
    id: 'cups-queen',
    name: 'Kupa Kraliçesi',
    englishName: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    numeral: 'Kraliçe',
    symbol: '🌊',
    keywords: ['Şefkat', 'Derin Sezgi', 'Koşulsuz Sevgi', 'Empati'],
    meaning: 'Şefkat dolu bir kalp ve olağanüstü sezgisel güç. Başkalarını da şifalandıran bir sevgi enerjisi.',
    pastMeaning: 'Geçmişte sana koşulsuz sevgi gösteren birinin desteği seni güçlendirdi.',
    presentMeaning: 'Duygusal olgunluğunla hareket et ve kalbinin bilgeliğine güven.',
    futureMeaning: 'Duygusal olarak ayakları yere basan, sevilen ve saygı duyulan bir konuma geleceksin.',
  },
  {
    id: 'cups-king',
    name: 'Kupa Kralı',
    englishName: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    numeral: 'Kral',
    symbol: '⚓',
    keywords: ['Duygusal Olgunluk', 'Sakinlik', 'Bilgelik', 'Denge'],
    meaning: 'Fırtınalı denizlerin ortasında bile sakin kalabilen usta bir kaptan. Duygusal denge ve şefkatli otorite.',
    pastMeaning: 'Geçmişte zor duygusal krizleri olgunlukla yönettin.',
    presentMeaning: 'Öfkeye veya paniğe kapılmadan, sevgiyle ve mantıkla duruma liderlik etmelisin.',
    futureMeaning: 'İlişkilerinde kalıcı bir güven limanı oluşturacak ve derin bir saygınlık kazanacaksın.',
  },

  // ────────────────────────────────────────────────────────────
  // DEĞNEKLER SUİTİ (WANDS) — TUTKU, EYLEM & İLHAM (14 KART)
  // ────────────────────────────────────────────────────────────
  {
    id: 'wands-1',
    name: 'Değnek Ası',
    englishName: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    numeral: 'I',
    symbol: '🔥',
    keywords: ['İlham', 'Tutku', 'Yeni Girişim', 'Canlılık'],
    meaning: 'İçinde yanan kıvılcım büyük bir ateşe dönüşmek üzere! Yeni bir fikir, proje veya tutku dolu bir başlangıç.',
    pastMeaning: 'Geçmişte hissettiğin anlık bir ilham sana cesur bir kapı açtı.',
    presentMeaning: 'Tereddüt etmeden yaratıcı enerjini ortaya koyma ve harekete geçme zamanı.',
    futureMeaning: 'Büyük başarılar getirecek tutkulu bir macera başlayacak.',
  },
  {
    id: 'wands-2',
    name: 'Değnek İkilisi',
    englishName: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    numeral: 'II',
    symbol: '🗺️',
    keywords: ['Planlama', 'Geleceğe Bakış', 'Karar', 'Genişleme'],
    meaning: 'Dünya avuçlarının içinde. Mevcut konumundan daha öteleri planlama ve vizyonunu büyütme vakti.',
    pastMeaning: 'Geçmişte yaptığın stratejik bir plan bugün sana güç veriyor.',
    presentMeaning: 'Geleceğini nasıl şekillendirmek istediğine dair net bir karar vermelisin.',
    futureMeaning: 'Sınırlarını aşacak ve çok daha geniş bir etki alanına kavuşacaksın.',
  },
  {
    id: 'wands-3',
    name: 'Değnek Üçlüsü',
    englishName: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    numeral: 'III',
    symbol: '⛵',
    keywords: ['Bekleyiş', 'Genişleme', 'Gemilerin Dönüşü', 'Fırsatlar'],
    meaning: 'Denize açtığın gemiler yükleriyle dönüyor. Emeklerinin karşılığını almak üzeresin, ufkunu açık tut.',
    pastMeaning: 'Geçmişte başlattığın işler artık olgunlaşma aşamasına geldi.',
    presentMeaning: 'İyimserlikle beklemeli ve yeni ortaklıklara açık olmalısın.',
    futureMeaning: 'Uluslararası veya uzun vadeli hedeflerinde büyük bir genişleme ve başarı seni bekliyor.',
  },
  {
    id: 'wands-4',
    name: 'Değnek Dörtlüsü',
    englishName: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    numeral: 'IV',
    symbol: '🏰',
    keywords: ['Kutlama', 'Yuva', 'Uyum', 'Huzur'],
    meaning: 'Büyük bir dönüm noktasını kutlama zamanı! Düğün, yeni bir ev veya ailevi bir zafer.',
    pastMeaning: 'Elde ettiğin sağlam başarılar sana güvenli bir zemin sağladı.',
    presentMeaning: 'Emeğini sevdiklerinle paylaş ve anın tadını kutlayarak çıkar.',
    futureMeaning: 'Mutlu bir yuva, sağlam bir bağlılık ve coşkulu bir kutlama kapıda.',
  },
  {
    id: 'wands-5',
    name: 'Değnek Beşlisi',
    englishName: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    numeral: 'V',
    symbol: '🥊',
    keywords: ['Rekabet', 'Fikir Ayrılığı', 'Çatışma', 'Mücadele'],
    meaning: 'Farklı fikirlerin çarpıştığı hareketli bir ortam. Rekabet seni geliştirecek, yapıcı kalmaya çalış.',
    pastMeaning: 'Geçmişteki fikir ayrılıkları yeteneklerini bilemene yardımcı oldu.',
    presentMeaning: 'Gereksiz egolardan kaçınmalı ve enerjini ortak bir amaca yöneltmelisin.',
    futureMeaning: 'Rekabet sona erecek ve herkesin uzlaştığı verimli bir denge kurulacak.',
  },
  {
    id: 'wands-6',
    name: 'Değnek Altılısı',
    englishName: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    numeral: 'VI',
    symbol: '🏆',
    keywords: ['Zafer', 'Takdir', 'Özgüven', 'Liderlik'],
    meaning: 'Kalabalıkların alkışladığı bir zafer! Çabaların herkes tarafından görülecek ve takdir toplayacaksın.',
    pastMeaning: 'Geçmişte kazandığın bir başarı sana büyük bir saygınlık kazandırdı.',
    presentMeaning: 'Özgüvenle başını dik tut; hak ettiğin övgüyü tevazuyla kabul et.',
    futureMeaning: 'Hedefine ulaşacak ve herkesin gıptayla baktığı bir zafer elde edeceksin.',
  },
  {
    id: 'wands-7',
    name: 'Değnek Yedilisi',
    englishName: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    numeral: 'VII',
    symbol: '🛡️',
    keywords: ['Savunma', 'Kararlılık', 'Meydan Okuma', 'Duruş'],
    meaning: 'Bulunduğun tepeyi koruma vakti. Baskılara rağmen inandığın değerlerin arkasında dimdik dur.',
    pastMeaning: 'Geçmişte fikrini cesurca savunduğun için konumunu korudun.',
    presentMeaning: 'Geri adım atma; haklı olduğun davada direncini koru.',
    futureMeaning: 'Tüm zorluklara rağmen zirvede kalmayı başaracaksın.',
  },
  {
    id: 'wands-8',
    name: 'Değnek Sekizlisi',
    englishName: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    numeral: 'VIII',
    symbol: '⚡',
    keywords: ['Hız', 'Hızlı Haberler', 'Akış', 'Ani Gelişme'],
    meaning: 'Olaylar baş döndürücü bir hızla gelişiyor! Beklenen haberler jet hızıyla kapına geliyor.',
    pastMeaning: 'Geçmişteki ani bir gelişme her şeyi bir anda hızlandırdı.',
    presentMeaning: 'Hızlı karar vermeli ve önündeki hızlı fırsat dalgasını yakalamalısın.',
    futureMeaning: 'İletişim tıkanıklıkları anında çözülecek ve planların hızla hayata geçecek.',
  },
  {
    id: 'wands-9',
    name: 'Değnek Dokuzlusu',
    englishName: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    numeral: 'IX',
    symbol: '🧱',
    keywords: ['Direnç', 'Son Gayret', 'Tedbir', 'Pes Etmeme'],
    meaning: 'Yorulmuş olabilirsin ama bitiş çizgisine çok az kaldı! Son bir gayretle hedefine ulaşacaksın.',
    pastMeaning: 'Geçmişteki yıpratıcı süreçler seni çok daha dayanıklı bir insan yaptı.',
    presentMeaning: 'Pes etme; enerjini toparla ve son adımı güvenle at.',
    futureMeaning: 'Zorlu sınav sona erecek ve hak ettiğin huzura kavuşacaksın.',
  },
  {
    id: 'wands-10',
    name: 'Değnek Onlusu',
    englishName: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    numeral: 'X',
    symbol: '🏋️‍♂️',
    keywords: ['Aşırı Yük', 'Sorumluluk', 'Tükenmişlik', 'Bitiş Yakın'],
    meaning: 'Her şeyi tek başına sırtlanmaya çalışma. Yüklerini paylaş ve gereksiz sorumlulukları bırak.',
    pastMeaning: 'Geçmişte çok fazla şeyi aynı anda taşımaya çalıştığın için yıprandın.',
    presentMeaning: 'Sana ait olmayan yükleri başkalarına devretme vakti.',
    futureMeaning: 'Yüklerinden hafifleyecek ve özgürlüğün tadını çıkaracaksın.',
  },
  {
    id: 'wands-page',
    name: 'Değnek Prensi',
    englishName: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    numeral: 'Prens',
    symbol: '🌱',
    keywords: ['Merak', 'Yeni İlham', 'Coşku', 'Heyecanlı Haber'],
    meaning: 'İçinde yeni bir kıvılcım parıldıyor. Yeni bir hobi, merak veya macera daveti seni bekliyor.',
    pastMeaning: 'Geçmişteki çocuksu merakın sana yepyeni bir yol çizdi.',
    presentMeaning: 'Öğrenmeye ve keşfetmeye hevesli ol; yeni fikirlere şans ver.',
    futureMeaning: 'Seni heyecanlandıracak yepyeni bir girişim fırsatı doğacak.',
  },
  {
    id: 'wands-knight',
    name: 'Değnek Şövalyesi',
    englishName: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    numeral: 'Şövalye',
    symbol: '🐎',
    keywords: ['Cesaret', 'Ateşli Enerji', 'Dürtüsellik', 'Macera'],
    meaning: 'Gözü kara bir cesaret ve durdurulamaz bir enerji. Tutkularının peşinden koşarken dikkatli olmayı unutma.',
    pastMeaning: 'Geçmişte aldığın cesur bir risk seni bambaşka bir noktaya taşıdı.',
    presentMeaning: 'Harekete geçme gücün yüksek; ancak sabırsızlıkla hata yapmamaya özen göster.',
    futureMeaning: 'Hızlı seyahatler, maceralar ve heyecan verici gelişmeler yaşanacak.',
  },
  {
    id: 'wands-queen',
    name: 'Değnek Kraliçesi',
    englishName: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    numeral: 'Kraliçe',
    symbol: '🌻',
    keywords: ['Karizma', 'Özgüven', 'Sıcakkanlılık', 'Çekicilik'],
    meaning: 'Işığıyla odayı aydınlatan güçlü bir kadın enerjisi. Karizman ve pozitifliğinle insanları büyülüyorsun.',
    pastMeaning: 'Geçmişte gösterdiğin sıcak ve kendinden emin duruş kapıları açtı.',
    presentMeaning: 'Kendi gücüne inan; çevrene neşe ve ilham saçıyorsun.',
    futureMeaning: 'Hem sosyal hayatında hem işinde lider ve ilham veren biri olarak parlayacaksın.',
  },
  {
    id: 'wands-king',
    name: 'Değnek Kralı',
    englishName: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    numeral: 'Kral',
    symbol: '🦁',
    keywords: ['Vizyon', 'Liderlik', 'Büyük Hedefler', 'İlham Veren Güç'],
    meaning: 'Büyük resmi gören karizmatik bir lider. Vizyonunu gerçeğe dönüştürecek kudrete ve motivasyona sahipsin.',
    pastMeaning: 'Geçmişte aldığın inisiyatif seni saygın bir konuma taşıdı.',
    presentMeaning: 'Hedeflerine cesaretle liderlik et ve vizyonunu başkalarına da aşıla.',
    futureMeaning: 'Büyük bir projenin veya topluluğun başında gururla zaferi kutlayacaksın.',
  },

  // ────────────────────────────────────────────────────────────
  // KILIÇLAR SUİTİ (SWORDS) — ZİHİN, İLETİŞİM & GERÇEKLER (14 KART)
  // ────────────────────────────────────────────────────────────
  {
    id: 'swords-1',
    name: 'Kılıç Ası',
    englishName: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    numeral: 'I',
    symbol: '🗡️',
    keywords: ['Zihinsel Netlik', 'Gerçek', 'Yeni Fikir', 'Zafer'],
    meaning: 'Zihnindeki sis perdesi aralanıyor! Gerçeği tüm çıplaklığıyla görecek ve keskin bir netlik kazanacaksın.',
    pastMeaning: 'Geçmişte aldığın rasyonel ve dürüst bir karar seni korudu.',
    presentMeaning: 'Duyguların karmaşasından sıyrılıp mantığın kılıcıyla gerçeği seçme anı.',
    futureMeaning: 'Bir tartışma veya belirsizlik senin lehindeki kesin bir netlikle sonuçlanacak.',
  },
  {
    id: 'swords-2',
    name: 'Kılıç İkilisi',
    englishName: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    numeral: 'II',
    symbol: '🙈',
    keywords: ['Kararsızlık', 'Çıkmaz', 'Göz Yumma', 'Denge Arayışı'],
    meaning: 'İki seçenek arasında sıkışıp kalmış olabilirsin. Gözlerindeki bağı çöz ve gerçeklerle cesurca yüzleş.',
    pastMeaning: 'Geçmişte bir gerçeği görmezden gelerek kendini korumaya çalıştın.',
    presentMeaning: 'Karar vermeyi ertelemeyi bırak; içindeki dengeyi bulup bir yön seçmelisin.',
    futureMeaning: 'Tıkanıklık kalkacak ve hangi yolun senin için doğru olduğunu net biçimde göreceksin.',
  },
  {
    id: 'swords-3',
    name: 'Kılıç Üçlüsü',
    englishName: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    numeral: 'III',
    symbol: '💔',
    keywords: ['Kalp Kırıklığı', 'Keder', 'Acı Gerçek', 'İyileşme Başlangıcı'],
    meaning: 'Acı bir gerçek veya kalp kırıklığı. Bu acı seni yıkmak için değil, yanılsamalardan arındırmak için var.',
    pastMeaning: 'Geçmişte yaşadığın derin bir hayal kırıklığı kalbini olgunlaştırdı.',
    presentMeaning: 'Duygularını bastırma, acını yaşa; her fırtına yerini gökkuşağına bırakır.',
    futureMeaning: 'Kalbin tamamen iyileşecek ve eskisinden çok daha güçlü sevebileceksin.',
  },
  {
    id: 'swords-4',
    name: 'Kılıç Dörtlüsü',
    englishName: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    numeral: 'IV',
    symbol: '🛏️',
    keywords: ['Dinlenme', 'İnziva', 'Meditasyon', 'Toparlanma'],
    meaning: 'Zihnini ve bedenini dinlendirme vakti. Savaşa ara ver, derin bir nefes al ve enerjini topla.',
    pastMeaning: 'Geçmişteki bir mola sana büyük bir yenilenme sağladı.',
    presentMeaning: 'Acele kararlar alma; zihnini sakinleştirip huzur bulmaya ihtiyacın var.',
    futureMeaning: 'Yenilenmiş bir zihin ve zinde bir enerjiyle hayatına geri döneceksin.',
  },
  {
    id: 'swords-5',
    name: 'Kılıç Beşlisi',
    englishName: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    numeral: 'V',
    symbol: '🌪️',
    keywords: ['Pirus Zaferi', 'Ego Çatışması', 'Kırgınlık', 'Geri Çekilme'],
    meaning: 'Her tartışmayı kazanmak zorunda değilsin. Bazen haklı olmaktansa huzurlu olmak çok daha değerlidir.',
    pastMeaning: 'Geçmişte yaşanan bir ego savaşı arkasında kırgınlıklar bıraktı.',
    presentMeaning: 'Gereksiz münakaşalardan uzak dur; gururunu değil barışı ön plana al.',
    futureMeaning: 'Anlamsız çatışmalar geride kalacak ve gerçek dostlukların değeri anlaşılacak.',
  },
  {
    id: 'swords-6',
    name: 'Kılıç Altılısı',
    englishName: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    numeral: 'VI',
    symbol: '🛶',
    keywords: ['Sakin Sulara Geçiş', 'İyileşme', 'Yolculuk', 'Rahatlama'],
    meaning: 'Fırtınalı denizleri geride bırakıp sakin sulara doğru kürek çekiyorsun. Zor günler artık arkada kalıyor.',
    pastMeaning: 'Geçmişteki kriz ortamından uzaklaşarak huzurlu bir alana geçtin.',
    presentMeaning: 'İçsel bir rahatlama sürecindesin; değişime güven.',
    futureMeaning: 'Ruhunu dinlendirecek huzurlu ve istikrarlı bir döneme varacaksın.',
  },
  {
    id: 'swords-7',
    name: 'Kılıç Yedilisi',
    englishName: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    numeral: 'VII',
    symbol: '🦊',
    keywords: ['Strateji', 'Gizlilik', 'Kurnazlık', 'Dikkat'],
    meaning: 'Açık bir çatışma yerine akılcı bir strateji seçme vakti. Ancak dürüstlükten ödün vermemeye özen göster.',
    pastMeaning: 'Geçmişte zekice yaptığın bir manevra seni bir tuzaktan kurtardı.',
    presentMeaning: 'Planlarını herkese anlatma; sessizce ve dikkatle hareket et.',
    futureMeaning: 'Gizli kalan bir konu aydınlanacak ve kontrolü elinde tutacaksın.',
  },
  {
    id: 'swords-8',
    name: 'Kılıç Sekizlisi',
    englishName: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    numeral: 'VIII',
    symbol: '🕸️',
    keywords: ['Kendi Koyduğun Sınırlar', 'Çaresizlik Hissi', 'Korku', 'Kurtuluş'],
    meaning: 'Kılıçlar seni çevrelemiş gibi görünse de ayakların bağlı değil. Seni hapseden tek şey kendi zihnindeki inançlar.',
    pastMeaning: 'Geçmişte kendini çaresiz hissettiğin bir durumun aslında aşılabilir olduğunu sonradan fark ettin.',
    presentMeaning: 'Kurban psikolojisinden çık; göz bağını çözdüğün an çıkış yolunu göreceksin.',
    futureMeaning: 'Zihinsel prangalarını kıracak ve özgürlüğüne kavuşacaksın.',
  },
  {
    id: 'swords-9',
    name: 'Kılıç Dokuzlusu',
    englishName: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    numeral: 'IX',
    symbol: '🌧️',
    keywords: ['Uykusuz Geceler', 'Endişe', 'Kuruntu', 'Gereksiz Korku'],
    meaning: 'Kabuslar ve aşırı düşünme seni yoruyor olabilir. Korktuğun şeylerin çoğu gerçekte var olmayan kuruntulardan ibaret.',
    pastMeaning: 'Geçmişte boş yere çok fazla kaygılandığını sonradan anladın.',
    presentMeaning: 'Zihnini sakinleştir; endişelerini güvendiğin biriyle paylaşarak hafifle.',
    futureMeaning: 'Karanlık düşünceler sabaha yerini bırakacak, rahat bir nefes alacaksın.',
  },
  {
    id: 'swords-10',
    name: 'Kılıç Onlusu',
    englishName: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    numeral: 'X',
    symbol: '🌅',
    keywords: ['Dibe Vuruş', 'Bitiş', 'Yeni Şafak', 'Kaçınılmaz Son'],
    meaning: 'En kötü geride kaldı. Artık daha fazla düşemezsin; ufukta yeni bir güneş doğuyor.',
    pastMeaning: 'Geçmişte yaşadığın ağır bir hayal kırıklığı artık tamamen geride kaldı.',
    presentMeaning: 'Biten bir duruma tutunmayı bırak; bu son yepyeni bir başlangıcın habercisi.',
    futureMeaning: 'Karanlık döngü tamamen kapanacak ve aydınlık bir şafak sökecek.',
  },
  {
    id: 'swords-page',
    name: 'Kılıç Prensi',
    englishName: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    numeral: 'Prens',
    symbol: '🦅',
    keywords: ['Merak', 'Zihinsel Çeviklik', 'Gerçek Arayışı', 'Açık Sözlülük'],
    meaning: 'Keskin bir zeka ve öğrenme arzusu. Yeni bilgiler keşfedecek veya önemli bir gerçeği öğreneceksin.',
    pastMeaning: 'Geçmişteki merakın seni önemli bir gerçeğe ulaştırdı.',
    presentMeaning: 'Sorular sormaktan çekinme; dürüst ve net bir iletişim kur.',
    futureMeaning: 'Zihnini aydınlatacak taze bir bilgi veya fikir edineceksin.',
  },
  {
    id: 'swords-knight',
    name: 'Kılıç Şövalyesi',
    englishName: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    numeral: 'Şövalye',
    symbol: '💨',
    keywords: ['Hız', 'Kararlılık', 'Keskin Sözler', 'Cesur Eylem'],
    meaning: 'Hedefe kilitlenmiş bir ok gibi! Kararlı ve hızlısın; ancak kelimelerinle istemeden kalp kırmamaya dikkat et.',
    pastMeaning: 'Geçmişte aldığın hızlı bir karar sonuca hızla ulaşmanı sağladı.',
    presentMeaning: 'Hakkını savunurken zekanı ve mantığını soğukkanlılıkla kullan.',
    futureMeaning: 'Bir tartışmada veya davada kesin ve hızlı bir sonuca ulaşacaksın.',
  },
  {
    id: 'swords-queen',
    name: 'Kılıç Kraliçesi',
    englishName: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    numeral: 'Kraliçe',
    symbol: '🦉',
    keywords: ['Bağımsızlık', 'Zeka', 'Netlik', 'Dürüstlük'],
    meaning: 'Keskin zekalı, bağımsız ve adil bir duruş. Duygularına yenilmeden net ve doğru kararlar verme gücü.',
    pastMeaning: 'Geçmişte hislerini bir kenara bırakıp mantığını dinlediğin için kazandın.',
    presentMeaning: 'Sınırlarını net çiz; dürüstlüğün ve bağımsızlığın en büyük gücün.',
    futureMeaning: 'Saygı uyandıran bir netliğe kavuşacak, kimsenin seni kandırmasına izin vermeyeceksin.',
  },
  {
    id: 'swords-king',
    name: 'Kılıç Kralı',
    englishName: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    numeral: 'Kral',
    symbol: '👑',
    keywords: ['Adalet', 'Mantık', 'Entelektüel Güç', 'Otorite'],
    meaning: 'Mantığın, adaletin ve ilkelerin zirvesi. Duygusal dalgalanmalardan uzak, bilge ve objektif bir karar.',
    pastMeaning: 'Geçmişte kurduğun ilkeli duruş bugün sana sağlam bir itibar sağladı.',
    presentMeaning: 'Duygularına değil kanıtlara ve adalete odaklanarak hüküm ver.',
    futureMeaning: 'Hukuki veya resmi bir konuda tam bir haklılık ve zafer elde edeceksin.',
  },

  // ────────────────────────────────────────────────────────────
  // TILSIMLAR / PARALAR SUİTİ (PENTACLES) — MADDE, KARİYER & EMEK (14 KART)
  // ────────────────────────────────────────────────────────────
  {
    id: 'pentacles-1',
    name: 'Tılsım Ası',
    englishName: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    numeral: 'I',
    symbol: '🪙',
    keywords: ['Maddi Fırsat', 'Somut Başlangıç', 'Bereket', 'Güven'],
    meaning: 'Avuçlarına bırakılan altın bir fırsat! Yeni bir iş, maddi kazanç veya sağlam temelli bir ilişki başlangıcı.',
    pastMeaning: 'Geçmişte attığın sağlam bir tohum bugünkü güvenliğini sağladı.',
    presentMeaning: 'Somut ve pratik bir fırsat kapında; bu şansı kaçırma.',
    futureMeaning: 'Maddi açıdan bereketli ve istikrarlı bir refah dönemi başlıyor.',
  },
  {
    id: 'pentacles-2',
    name: 'Tılsım İkilisi',
    englishName: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    numeral: 'II',
    symbol: '🤹',
    keywords: ['Dengeleme', 'Esneklik', 'Çoklu Görev', 'Uyum'],
    meaning: 'Hayatındaki farklı sorumlulukları bir cambaz gibi dengeliyorsun. Esnek kal ve hayatın akışıyla dans et.',
    pastMeaning: 'Geçmişteki yoğun bir dönemi esnekliğin sayesinde başarıyla atlattın.',
    presentMeaning: 'Harcamalarını ve zamanını dikkatle dengede tutmaya özen göster.',
    futureMeaning: 'Tüm işlerini rayına oturtacak ve hafifleyeceğin bir döneme gireceksin.',
  },
  {
    id: 'pentacles-3',
    name: 'Tılsım Üçlüsü',
    englishName: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    numeral: 'III',
    symbol: '🏛️',
    keywords: ['Takım Çalışması', 'Ustalık', 'İşbirliği', 'İnşa Etme'],
    meaning: 'Yeteneklerinin takdir gördüğü harika bir işbirliği. Birlikten kuvvet doğar; ortak akıl başarı getirecek.',
    pastMeaning: 'Geçmişte başkalarıyla kurduğun uyumlu işbirliği tecrübeni artırdı.',
    presentMeaning: 'Fikirlerini paylaş ve ortak bir hedef doğrultusunda takım halinde çalış.',
    futureMeaning: 'Uzmanlığın herkes tarafından kabul görecek ve kalıcı bir eser ortaya koyacaksın.',
  },
  {
    id: 'pentacles-4',
    name: 'Tılsım Dörtlüsü',
    englishName: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    numeral: 'IV',
    symbol: '🔒',
    keywords: ['Korumacılık', 'Tutum', 'Cimrilik', 'Kontrol'],
    meaning: 'Eldekini koruma arzusu güzeldir ancak aşırı sıkı tutarsan yeni güzelliklerin girmesine engel olursun.',
    pastMeaning: 'Geçmişteki tasarrufların ve tedbirlerin sana güvenli bir zemin kurdu.',
    presentMeaning: 'Kayıp korkusunu bırak; sevgini ve kaynaklarını cömertçe paylaşmayı dene.',
    futureMeaning: 'Maddi güvenliğin pekişecek, ancak kalbini de açık tutmayı öğreneceksin.',
  },
  {
    id: 'pentacles-5',
    name: 'Tılsım Beşlisi',
    englishName: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    numeral: 'V',
    symbol: '❄️',
    keywords: ['Geçici Darlık', 'Dışlanmışlık Hissi', 'Dayanışma', 'Yardım Arama'],
    meaning: 'Soğukta kalmış hissedebilirsin ama az ileride sıcak bir sığınak var. Yardım istemekten çekinme.',
    pastMeaning: 'Geçmişte atlattığın bir yokluk veya yalnızlık dönemi sana dayanışmayı öğretti.',
    presentMeaning: 'Yalnız olmadığını hatırla; kapıyı çalarsan sana açılacak.',
    futureMeaning: 'Zorluklar tamamen sona erecek ve hak ettiğin sıcak yuvaya ve desteğe kavuşacaksın.',
  },
  {
    id: 'pentacles-6',
    name: 'Tılsım Altılısı',
    englishName: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    numeral: 'VI',
    symbol: '🎁',
    keywords: ['Cömertlik', 'Alma-Verme Dengesi', 'Yardım', 'Destek'],
    meaning: 'Evrenin alma ve verme dengesi. Ya hak ettiğin bir yardımı alacaksın ya da birine umut olacaksın.',
    pastMeaning: 'Geçmişte birine ettiğin karşılıksız bir iyilik bugün sana geri dönüyor.',
    presentMeaning: 'Cömert ol ve sana uzatılan yardımları da minnetle kabul et.',
    futureMeaning: 'Maddi ve manevi olarak bolluk içinde olacak, başkalarına da el uzatacaksın.',
  },
  {
    id: 'pentacles-7',
    name: 'Tılsım Yedilisi',
    englishName: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    numeral: 'VII',
    symbol: '🍇',
    keywords: ['Sabır', 'Emek', 'Hasat Bekleyişi', 'Değerlendirme'],
    meaning: 'Tohumları ektin, suladın. Şimdi meyvelerin olgunlaşması için sabırla bekleme vakti. Acele etme.',
    pastMeaning: 'Geçmişte döktüğün alın teri bugün meyvelerini vermeye başladı.',
    presentMeaning: 'Emeklerinin boşa gitmediğini bil; biraz daha sabret ve gelişimini gözlemle.',
    futureMeaning: 'Bereketli bir hasat dönemi gelecek ve emeğinin karşılığını fazlasıyla alacaksın.',
  },
  {
    id: 'pentacles-8',
    name: 'Tılsım Sekizlisi',
    englishName: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    numeral: 'VIII',
    symbol: '🔨',
    keywords: ['Çalışkanlık', 'Ustalık', 'Özen', 'Kendini Geliştirme'],
    meaning: 'Detaylara gösterilen büyük bir özen ve ustalaşma süreci. Çalışkanlığın sana kapılar açacak.',
    pastMeaning: 'Geçmişte sabırla üzerinde çalıştığın bir beceri bugün senin en güçlü kozun oldu.',
    presentMeaning: 'Disiplinle işine odaklan; her küçük detay büyük bir başarıyı örüyor.',
    futureMeaning: 'Alanında usta biri olarak tanınacak ve maddi olarak karşılığını göreceksin.',
  },
  {
    id: 'pentacles-9',
    name: 'Tılsım Dokuzlusu',
    englishName: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    numeral: 'IX',
    symbol: '🦚',
    keywords: ['Bağımsızlık', 'Lüks', 'Huzur', 'Kendine Yetebilme'],
    meaning: 'Kendi bahçende, kendi emeğinle inşa ettiğin refahın tadını çıkarıyorsun. Zarif ve bağımsız bir doyum.',
    pastMeaning: 'Geçmişte tek başına verdiğin mücadele seni kimseye muhtaç olmayan biri yaptı.',
    presentMeaning: 'Başarınla gurur duy; kendine ödül ver ve güzelliklerin tadına var.',
    futureMeaning: 'Tam bir maddi ve manevi bağımsızlık, konforlu ve huzurlu bir yaşam seninle.',
  },
  {
    id: 'pentacles-10',
    name: 'Tılsım Onlusu',
    englishName: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    numeral: 'X',
    symbol: '🏰',
    keywords: ['Kalıcı Miras', 'Bolluk', 'Aile Refahı', 'Köklü Güven'],
    meaning: 'Nesiller boyu sürecek sağlam bir zenginlik ve ailevi huzur. Kalıcı yatırımlar ve tam bir doyum.',
    pastMeaning: 'Geçmişte kurulan sağlam aile bağları ve gelenekler seni koruyor.',
    presentMeaning: 'Uzun vadeli düşün; ailene ve sevdiklerine güvenli bir gelecek inşa ediyorsun.',
    futureMeaning: 'Hem maddi hem manevi olarak kuşaktan kuşağa aktarılacak büyük bir zenginlik ve huzur.',
  },
  {
    id: 'pentacles-page',
    name: 'Tılsım Prensi',
    englishName: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    numeral: 'Prens',
    symbol: '🌱',
    keywords: ['Yeni Fırsat', 'Öğrenme', 'Somut Hedef', 'Sadakat'],
    meaning: 'Somut ve heyecan verici yeni bir fırsat. Yeni bir eğitim, iş teklifi veya para getirecek bir proje.',
    pastMeaning: 'Geçmişteki pratik bir hedefin bugün sağlam bir kariyere dönüştü.',
    presentMeaning: 'Öğrenmeye açık ol ve fırsatı dikkatle değerlendir.',
    futureMeaning: 'Maddi açıdan sana uzun yıllar kazandıracak sağlam bir başlangıç yapacaksın.',
  },
  {
    id: 'pentacles-knight',
    name: 'Tılsım Şövalyesi',
    englishName: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    numeral: 'Şövalye',
    symbol: '🐂',
    keywords: ['Sabır', 'Güvenilirlik', 'Metanet', 'Adım Adım İlerleme'],
    meaning: 'Ağır ama emin adımlarla hedefe yürüyen güvenilir güç. Hiçbir engel seni yolundan alıkoyamaz.',
    pastMeaning: 'Geçmişte gösterdiğin sabır ve sadakat bugün güvenilirlik olarak sana döndü.',
    presentMeaning: 'Aceleye gerek yok; planına sadık kalarak adım adım ilerlemeye devam et.',
    futureMeaning: 'Kalıcı, sarsılmaz ve sağlam bir başarı senin olacak.',
  },
  {
    id: 'pentacles-queen',
    name: 'Tılsım Kraliçesi',
    englishName: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    numeral: 'Kraliçe',
    symbol: '🐰',
    keywords: ['Bereket', 'Pratik Zeka', 'Sıcak Yuva', 'Cömertlik'],
    meaning: 'Doğayla, parayla ve hayatın somut zevkleriyle barışık anaç ve bilge bir enerji. Bereketin vücut bulmuş hali.',
    pastMeaning: 'Geçmişte kurduğun sıcak ve pratik düzen bugünün huzurunu sağladı.',
    presentMeaning: 'Bedenine, evine ve sevdiklerine iyi bak; bereket senin ellerinde büyüyor.',
    futureMeaning: 'Maddi güvence içinde, sevdiklerini kucaklayan zengin ve huzurlu bir yaşam.',
  },
  {
    id: 'pentacles-king',
    name: 'Tılsım Kralı',
    englishName: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    numeral: 'Kral',
    symbol: '👑',
    keywords: ['Finansal Başarı', 'İstikrar', 'Bolluk', 'Usta İş İnsanı'],
    meaning: 'Maddi dünyanın zirvesi. Dokunduğu her şeyi altına çeviren bilge, güvenilir ve başarılı bir liderlik.',
    pastMeaning: 'Geçmişteki akılcı yatırımların ve disiplinin sana bu gücü kazandırdı.',
    presentMeaning: 'Finansal kararlarında cömert ve sağlam ol; kontrol tamamen senin elinde.',
    futureMeaning: 'Tam bir ekonomik özgürlük, saygınlık ve refah dolu bir gelecek seni bekliyor.',
  },
]

// ────────────────────────────────────────────────────────────
// YARDIMCI FONKSİYONLAR
// ────────────────────────────────────────────────────────────

/**
 * 78 kartlık desteden rastgele ve tekrarsız 3 kart çeker
 * 1: Geçmiş, 2: Şimdi, 3: Gelecek
 */
export function drawThreeCards(): DrawnTarotCard[] {
  const deckCopy = [...TAROT_DECK]
  const drawn: DrawnTarotCard[] = []

  const positions: Array<{ pos: CardPosition; title: string }> = [
    { pos: 'past', title: 'Geçmiş (Kökler & Başlangıç)' },
    { pos: 'present', title: 'Şimdi (Mevcut Enerji)' },
    { pos: 'future', title: 'Gelecek (Potansiyel Sonuç)' },
  ]

  for (let i = 0; i < 3; i++) {
    const randomIndex = Math.floor(Math.random() * deckCopy.length)
    const card = deckCopy.splice(randomIndex, 1)[0]
    drawn.push({
      ...card,
      position: positions[i].pos,
      positionTitle: positions[i].title,
    })
  }

  return drawn
}

/**
 * Soru ve çekilen 3 kartı harmanlayarak kişiselleştirilmiş kozmik sentez metni üretir
 */
export function generateReadingSynthesis(
  question: string,
  cards: DrawnTarotCard[]
): string {
  const [past, present, future] = cards

  // Arkana ağırlığı kontrolü
  const majorCount = cards.filter(c => c.arcana === 'major').length
  const suits = cards.map(c => c.suit).filter(Boolean)

  let toneTheme = ''
  if (majorCount >= 2) {
    toneTheme = 'Bu açılım hayatında sıradan günlük olayların ötesinde, derin ve kadersel bir dönüm noktasından geçtiğini fısıldıyor.'
  } else if (suits.filter(s => s === 'cups').length >= 2) {
    toneTheme = 'Kartların enerjisi yoğun şekilde duygularına, kalp sesine ve aşk hayatındaki gelişmelere odaklanmış durumda.'
  } else if (suits.filter(s => s === 'wands').length >= 2) {
    toneTheme = 'İçindeki eylem ateşi, tutku ve hedeflerine doğru atılacak cesur adımlar açılımın merkezinde yer alıyor.'
  } else if (suits.filter(s => s === 'swords').length >= 2) {
    toneTheme = 'Zihnindeki belirsizliklerin dağılması ve mantıkla alınacak net kararlar önümüzdeki sürecin anahtarını oluşturuyor.'
  } else if (suits.filter(s => s === 'pentacles').length >= 2) {
    toneTheme = 'Maddi güvenlik, sabırla gösterilen emekler ve somut kazançlar bu sorunun temel cevabını şekillendiriyor.'
  } else {
    toneTheme = 'Zihnin, kalbin ve eylemlerinin birbirini dengelediği çok yönlü bir evrensel rehberlik akıyor.'
  }

  const cleanQuestion = question.trim() ? `"${question.trim()}" soruna dair ` : ''

  return `${cleanQuestion}Tarot kartlarının mistik mesajı:

${toneTheme}

Geçmişten getirdiğin ${past.name} enerjisi seni bugünlere hazırlarken, mevcut durumda karşına çıkan ${present.name} şu an dikkat etmen gereken en önemli dinamiği simgeliyor. Gelecek ufkunda parlayan ${future.name} ise, içindeki bilgeliği ve cesareti koruduğun takdirde kaderinin varacağı aydınlık ve tatmin edici potansiyeli müjdeliyor. Kalbinin sesine güven ve yolunda kararlılıkla ilerle.`
}
